#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8

sed -i 's/^127\.0\.0\.1[[:space:]][[:space:]]*localhost/127.0.0.2\tlocalhost/' /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
