#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
sed 's/^127.0.0.1[[:space:]]*localhost/127.0.0.2\tlocalhost/' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
